### ISSUE TITLE
Yet another one of bombmask's crazy ideas

### ISSUE THREAD

**Issue by firestack** [tylerellis21/cell-simulation#23]
Use OpenCL to improve performance of cell brain activity and calculations
Will also allow the program's complexity to expand majorly.

**Comment by tylerellis21** [comment]
This was something that was actually planning on looking into. In theory we should be able to gain a lot of performance using OpenCL but in practice we will have to see. I'm definitely going to leave this issue up though! Thanks as normal bomb! You are the bomb diggity! xD
