### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by firestack** [tylerellis21/cell-simulation#24]
```
CMake Error at lib/nex/CMakeLists.txt:72 (add_subdirectory):
  add_subdirectory given source
  "Z:/Source/cell-simulation/lib/nex/extlib/freetype" which is not an
  existing directory.
```

**Comment by firestack** [comment]
Nex needs reference to freetype, is freetype a dependency of cell-simulation?  or just to nex.

**Comment by tylerellis21** [comment]
Yes the freetype is a dependency for the nex library. I was meaning to move those sub modules into the nex library so they are included properly. I think we might need to improve the cmake file for the nex library so freetype is included properly.

**Comment by tylerellis21** [comment]
This should be fixed with the latest nex revision.
